"""Pydantic models for Contract Generator endpoints.

Phase 8: Contract Generator — questionnaire request and generation response.
"""

from typing import Literal

from pydantic import BaseModel


class ContractGenerationRequest(BaseModel):
    """Questionnaire input for generating a contract document.

    Required:
        contract_type: One of "nda", "service", "employment", "contractor"

    All other fields are optional and will use sensible defaults or
    placeholder text if not provided.
    """
    contract_type: Literal["nda", "service", "employment", "contractor"]

    # Party information
    party_a_name: str | None = None
    party_b_name: str | None = None

    # General terms
    effective_date: str | None = None  # ISO date string
    governing_state: str | None = None
    term_months: int | None = None
    notice_days: int | None = None
    purpose: str | None = None

    # Service / contractor
    scope_of_services: str | None = None
    payment_amount: str | None = None
    payment_schedule: str | None = None
    payment_net_days: str | None = None
    contractor_rate: str | None = None

    # Employment
    job_title: str | None = None
    job_duties: str | None = None
    salary: str | None = None
    pay_schedule: str | None = None

    # IP
    ip_owner: str | None = None

    # Restrictive covenants
    non_compete_months: str | None = None
    non_compete_geography: str | None = None
    non_solicit_months: str | None = None


class ContractTypeInfo(BaseModel):
    """Available contract type for the questionnaire."""
    id: str
    label: str


class ContractTypesResponse(BaseModel):
    """List of available contract types."""
    ok: bool = True
    types: list[ContractTypeInfo]


class ContractGenerationResponse(BaseModel):
    """Response after generating a contract document."""
    ok: bool = True
    contract_id: str
    contract_type: str
    contract_label: str
    filename: str
    size_bytes: int
    download_url: str
    disclaimer: str = (
        "This document was generated by an automated system and does not "
        "constitute legal advice. Consult licensed counsel before use."
    )
